
input:
  redis:
    addresses: [127.0.0.1:16300,127.0.0.1:16310]
    type: cluster
channel:
  storer:
    dirPath: /tmp/redisgunyu-cluster3
    maxSize: 209715200
    logSize: 20971520
output:
  resumeFromBreakPoint: false
  keepaliveTicker: 600s
  redis:
    addresses: [127.0.0.1:6707]
    type: standalone
# log:
#   level: info
#   handler:
#     stdout: true
#   withCaller: false
#   withFunc: false
