server:
  listen: 127.0.0.1:18001
  listenPeer: 127.0.0.1:18001
  gracefullStopTimeout: 1s
  checkRedisTypologyTicker: 10s
input:
  redis:
    addresses: [127.0.0.1:6379]
    type: standalone
  mode: dynamic
  syncDelayTestKey: redis-GunYu-syncDelay-testKey
  syncFrom: prefer_slave
channel:
  storer:
    dirPath: /tmp/redisgunyu5
    maxSize: 1073741800
    logSize: 10971520
output:
  redis:
    addresses: [127.0.0.1:6479]
    type: standalone
log:
  level: info
  handler:
    stdout: true
cluster:
  groupName: redis1
  leaseTimeout: 9s
